apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: test
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: "Forbid"
  failedJobsHistoryLimit: 10
  startingDeadlineSeconds: 600
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 3300
      template:
        spec:
          containers:
            - name: metrics-exporter
              image: FIXME
              command: ["python"]
              args: ["./subnet.py"]
          restartPolicy: Never
